---
  - name: Install and Configure Database
    apt:
      name: ['mysql-server', 'mysql-client']
      state: present

  - name: Start Database Service
    systemd:
      name: mysql
      state: started
      enabled: yes

  - name: Create database and database users
    mysql_db:
      name: "{{ db_name }}"
      state: present

  - name: Create database user
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: '*.*:ALL'
      state: present
      host: '%'
